package adapters

func init() {
	Register(NewHTTPProbe())
	Register(NewSecurityHeaders())
	Register(NewWhatWeb())
	Register(NewNucleiTech())
	Register(NewTestSSL())
	Register(NewGraphQLIntrospection())
	Register(NewOpenAPIDiscovery())
	Register(NewWPScan())
	Register(NewDroopescan())
	Register(NewArjun())
	Register(NewLinkFinder())
	Register(NewGitleaks())
	Register(NewJavaScriptSecretScan())
	Register(NewCORSCheck())
	Register(NewCloudBucketCheck())
	Register(NewSubfinder())
	Register(NewDNSX())
	Register(NewNaabu())
	Register(NewHTTPX())
	Register(NewWhois())
	Register(NewWaybackURLs())
	Register(NewCrtSH())
	Register(NewNmap())
	Register(NewFFUF())
	Register(NewSQLMap())
	Register(NewDalfox())
}
